src/EnsekMeter.Web/Models/AccountViewModel.cs
namespace EnsekMeter.Web.Models
{
    public class AccountViewModel
    {
        public int AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

src/EnsekMeter.Web/Models/BulkUploadMeterReadingsViewModel.cs
using System.Collections.Generic;

namespace EnsekMeter.Web.Models
{
    public class BulkUploadMeterReadingsViewModel
    {
        public int SuccesfulUploads { get; set; }
        public int FailedUploads { get; set; }
        public List<string> UploadErrors { get; set; }
    }
}

src/EnsekMeter.Web/Models/ErrorViewModel.cs
namespace EnsekMeter.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/EnsekMeter.Web/Models/FileUploadViewModel.cs
using Microsoft.AspNetCore.Http;

namespace EnsekMeter.Web.Models
{
    public class FileUploadViewModel
    {
        public BulkUploadMeterReadingsViewModel Result { get; set; }
        public IFormFile FormFile { get; set; }
    }
}

src/EnsekMeter.Web/Models/MeterReading.cs
using System;

namespace EnsekMeter.Web.Models
{
    public class MeterReadingViewModel
    {
        public int MeterReadingId { get; set; }
        public int AccountId { get; set; }
        public DateTime MeterReadingDateTime { get; set; }
        public int MeterReadValue { get; set; }
    }
}

src/EnsekMeter.Web/Controllers/AccountsController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EnsekMeter.Web.Models;
using EnsekMeter.Web.Services;

namespace EnsekMeter.Web.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAccountService _accountService;

        public AccountsController(IAccountService accountService)
        {
            _accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _accountService.GetAccounts());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _accountService.GetAccount(id));
        }

        public async Task<IActionResult> Create()
        {
            await _accountService.GenerateAccounts();
            return RedirectToAction("Index");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/EnsekMeter.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EnsekMeter.Web.Models;

namespace EnsekMeter.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/EnsekMeter.Web/Controllers/MeterReadingsController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EnsekMeter.Web.Models;
using EnsekMeter.Web.Services;
using EnsekMeter.Web.Extentions;

namespace EnsekMeter.Web.Controllers
{
    public class MeterReadingsController : Controller
    {
        private readonly IMeterReadingService _meterReadingService;

        public MeterReadingsController(IMeterReadingService meterReadingService)
        {
            _meterReadingService = meterReadingService ?? throw new ArgumentNullException(nameof(meterReadingService));
        }
        
        public async Task<IActionResult> Details(int id)
        {
            return View(await _meterReadingService.GetMeterReading(id));
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Edit(int id)
        {
            return View(await _meterReadingService.GetMeterReading(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, MeterReadingViewModel meterReading)
        {
            try
            {
                await _meterReadingService.UpdateMeterReading(meterReading);
                return RedirectToAction("Details", "Accounts", new{id = meterReading.AccountId});
            }
            catch
            {
                return View();
            }
        }

        public IActionResult Create(int accountId)
        {
            return View(new MeterReadingViewModel{AccountId = accountId});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MeterReadingViewModel meterReading)
        {
            try
            {
                await _meterReadingService.AddMeterReading(meterReading);
                return RedirectToAction("Details", "Accounts", new { id = meterReading.AccountId });
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Delete(int id, int accountId)
        {
            await _meterReadingService.DeleteMeterReading(id);
            return RedirectToAction("Details", "Accounts", new { id = accountId });
        }

        public IActionResult Upload()
        {
            var result = TempData.Get<BulkUploadMeterReadingsViewModel>("uploadErrors");
            return View(new FileUploadViewModel{Result = result});
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Upload(FileUploadViewModel fileUpload)
        {
            try
            {
                var result = await _meterReadingService.BulkUploadMeterReadings(fileUpload);
                TempData.Put("uploadErrors", result);
                return RedirectToAction("Upload", "MeterReadings");
            }
            catch
            {
                return View();
            }
        }

    }
}

src/EnsekMeter.Web/ViewComponents/AccountMeterReadingsViewComponent.cs
using System;
using EnsekMeter.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace EnsekMeter.Web.ViewComponents
{
    public class AccountMeterReadingsViewComponent : ViewComponent
    {
        private readonly IMeterReadingService _meterReadingService;
        public AccountMeterReadingsViewComponent(IMeterReadingService meterReadingService)
        {
            _meterReadingService = meterReadingService ?? throw new ArgumentNullException(nameof(meterReadingService));
        }
        public IViewComponentResult Invoke(int accountId)
        {
            ViewBag.AccountId = accountId;
            return View(_meterReadingService.GetMeterReadings(accountId).Result);
        }
    }
}

src/EnsekMeter.Web/Views/Accounts/Components/AccountMeterReadings/Default.cshtml
@model IEnumerable<EnsekMeter.Web.Models.MeterReadingViewModel>

<p>
    @Html.ActionLink("Create New", "Create", "MeterReadings", new { accountId = ViewBag.AccountId  })
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MeterReadingId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeterReadingDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeterReadValue)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadingDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadValue)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "MeterReadings", new {  id=item.MeterReadingId  }) |
                @Html.ActionLink("Details", "Details", "MeterReadings", new {  id=item.MeterReadingId  }) |
                @Html.ActionLink("Delete", "Delete", "MeterReadings", new {  id=item.MeterReadingId, accountId=item.AccountId  })
            </td>
        </tr>
    }
    </tbody>
</table>

src/EnsekMeter.Web/Views/Accounts/Details.cshtml
@model EnsekMeter.Web.Models.AccountViewModel

<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>
<div>
    @await Component.InvokeAsync("AccountMeterReadings", new { accountId = Model.AccountId })
</div>
<div>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    <a asp-action="Index">Back to List</a>
</div>

src/EnsekMeter.Web/Views/Accounts/Index.cshtml
@model IEnumerable<EnsekMeter.Web.Models.AccountViewModel>

<p>
    <a asp-action="Create">Generate Accounts</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccountId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccountId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink("Details", "Details", new {  id=item.AccountId  })
                @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
}
    </tbody>
</table>

src/EnsekMeter.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Use the <b>Generate Accounts</b> link on the <b>Accounts</b> tab to fill the inMemory database with accounts</p>
    <p>On the <b>Upload Meter Readings</b> tab you can upload a csv file with Meter Readings</p>
    <p>On the <b>Accounts</b> tab you can browse all the accounts</p>
    <p>On the <b>Accounts Details</b> screen you can browse all the account's Meter Registrations and Add/Update/Delete them</p>
</div>

src/EnsekMeter.Web/Views/MeterReadings/Create.cshtml
@model EnsekMeter.Web.Models.MeterReadingViewModel

<h4>Meter Reading</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeterReadingId" class="control-label"></label>
                <input asp-for="MeterReadingId" class="form-control" />
                <span asp-validation-for="MeterReadingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <input asp-for="AccountId" class="form-control" />
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeterReadingDateTime" class="control-label"></label>
                <input asp-for="MeterReadingDateTime" class="form-control" />
                <span asp-validation-for="MeterReadingDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeterReadValue" class="control-label"></label>
                <input asp-for="MeterReadValue" class="form-control" />
                <span asp-validation-for="MeterReadValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/EnsekMeter.Web/Views/MeterReadings/Details.cshtml
@model EnsekMeter.Web.Models.MeterReadingViewModel

<div>
    <h4>Meter Reading</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeterReadingId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeterReadingId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeterReadingDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeterReadingDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeterReadValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeterReadValue)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.MeterReadingId  }) |
    @Html.ActionLink("Back to Account", "Details", "Accounts", new {  id = Model.AccountId  }) 
</div>

src/EnsekMeter.Web/Views/MeterReadings/Edit.cshtml
@model EnsekMeter.Web.Models.MeterReadingViewModel

<h4>Meter Reading</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeterReadingId" class="control-label"></label>
                <input asp-for="MeterReadingId" class="form-control" />
                <span asp-validation-for="MeterReadingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <input asp-for="AccountId" class="form-control" />
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeterReadingDateTime" class="control-label"></label>
                <input asp-for="MeterReadingDateTime" class="form-control" />
                <span asp-validation-for="MeterReadingDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeterReadValue" class="control-label"></label>
                <input asp-for="MeterReadValue" class="form-control" />
                <span asp-validation-for="MeterReadValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to Account", "Details", "Accounts", new { id = Model.AccountId })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/EnsekMeter.Web/Views/MeterReadings/Index.cshtml
@model IEnumerable<EnsekMeter.Web.Models.MeterReadingViewModel>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MeterReadingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccountId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeterReadingDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeterReadValue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadingDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadValue)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

src/EnsekMeter.Web/Views/MeterReadings/Upload.cshtml
@model EnsekMeter.Web.Models.FileUploadViewModel

<h4>Meter Reading</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" method="post">
            <dl>
                <dt>
                    <label asp-for="FormFile"></label>
                </dt>
                <dd>
                    <input asp-for="FormFile" type="file">
                    <span asp-validation-for="FormFile"></span>
                </dd>
            </dl>
            <input asp-page-handler="Upload" class="btn" type="submit" value="Upload" />
        </form>

    </div>
</div>
@if (Model.Result != null)
{
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Result.SuccesfulUploads)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Result.SuccesfulUploads)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Result.FailedUploads)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Result.FailedUploads)
        </dd>
        @foreach (var item in Model.Result.UploadErrors)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelitem => item)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelitem => item)
            </dd>
        }
    </dl>
}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/EnsekMeter.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnsekMeter.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Index">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MeterReadings" asp-action="Upload">Upload Meter Readings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EnsekMeter.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>